install httpfs;
load httpfs;
CREATE SECRET metagenomics_mac (
    TYPE gcs,
    KEY_ID 'KEY_ID',
    SECRET 'SECRET'
);
-- MetaPhlAn
copy (select * from read_csv('gs://metagenomics-mac/results/cMDv4/*/metaphlan_lists/metaphlan_viruses_list.tsv.gz', filename=True, delim='\t', comment='#', union_by_name=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/viral_clusters.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv('gs://metagenomics-mac/results/cMDv4/*/metaphlan_lists/metaphlan_unknown_list.tsv.gz', filename=True,  delim='\t', comment='#', union_by_name=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/relative_abundance.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/metaphlan_markers/marker_abundance.tsv.gz', filename=True, delim = '\t', comment='#', union_by_name=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/marker_abundance.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/metaphlan_markers/marker_presence.tsv.gz', filename=True, delim = '\t', comment='#', union_by_name=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/marker_presence.parquet' (format parquet, compression 'zstd');

-- HUMAnN
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_cpm.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_cpm.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_relab.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_relab.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_stratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_stratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_unstratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_unstratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_cpm_stratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_cpm_stratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_relab_stratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_relab_stratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_cpm_unstratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_cpm_unstratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_genefamilies_relab_unstratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/genefamilies_relab_unstratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_cpm.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_cpm.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_relab.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_relab.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_stratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_stratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_unstratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_unstratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_cpm_stratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_cpm_stratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_relab_stratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_relab_stratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_cpm_unstratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_cpm_unstratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathabundance_relab_unstratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathabundance_relab_unstratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathcoverage_unstratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathcoverage_unstratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathcoverage_stratified.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathcoverage_stratified.parquet' (format parquet, compression 'zstd');
copy (select * from read_csv_auto('gs://metagenomics-mac/results/cMDv4/*/humann/out_pathcoverage.tsv.gz', filename=True)) to '/shares/CIBIO-Storage/CM/scratch/users/kaelyn.long/retrieve/parquets/pathcoverage.parquet' (format parquet, compression 'zstd');
